### ISSUE TITLE
make emacs snapshot available

### ISSUE THREAD

**Issue by shackra** [alexmurray/emacs-snap#1]
What do we do from here and how we do it?

**Comment by alexmurray** [comment]
I suggest the easiest way to do this would be to maintain a separate branch for each track - feel free to submit a PR with your changes to support an emacs snapshot build and I'll merge it into a new snapshot branch and can then set up a new build via launchpad.net/emacs-snap and will apply to have a new snapshot track created where we can publish this to in the snap store.

**Comment by shackra** [comment]
I opened a pull request, please tell me if something else is required

**Comment by alexmurray** [comment]
Thanks - merged in 88d0618 - I have requested the new snapshot track from the store at https://forum.snapcraft.io/t/track-requests-26-2-and-snapshot-for-emacs/12502 so once the track is created, I will then create a new launchpad build recipe for this too at https://launchpad.net/emacs-snap

**Comment by shackra** [comment]
any updates?

**Comment by alexmurray** [comment]
I am still waiting to see if we can get appropriate tracks created for the snap. If not, I will look at publishing snapshot builds to latest/edge and leaving latest/stable as whatever the current release version is.

**Comment by alexmurray** [comment]
FYI - as per https://forum.snapcraft.io/t/track-requests-26-2-and-snapshot-for-emacs/12502/13 I have now enabled emacs-snapshot builds to get published to the `latest/edge` channel (this is currently building but assuming a successful build this should be available within the next hour or so)

So if you want to track this, you can install it as:
`snap install emacs --edge`
or if you already have the snap installed, you can switch to the edge track:
`snap refresh emacs --edge`

**Comment by shackra** [comment]
One question I have, and forgot to ask: the `--edge` channel how often rebuilds the package or is something that needs to be triggered manually?

**Comment by alexmurray** [comment]
These are triggered automatically every 24 hours at the moment... I am wondering if this is perhaps too often so this may be changed to be a bit less frequent in the future
