### ISSUE TITLE
Cannot open load file: No such file or directory, warnings

### ISSUE THREAD

**Issue by Sleepful** [alexmurray/emacs-snap#11]
### Cannot open load file: No such file or directory, warnings

I am using the snap with `emacs 27` (beta branch).
I get this error on emacs if I do not have emacs26 installed in my ubuntu LTS 18.04.1:
```
Autoload file error: autoloads.pkg.el -> (file-missing Cannot open load file No such file or directory cl)
startup--load-user-init-file: Cannot open load file: No such file or directory, warnings
```
However if I run:
`sudo apt-get install emacs26` (from the PPA, doesn't work with emacs25) 
and then I run:
`/snap/bin/emacs` 
I do not get any issue. I have no idea what's going on. If I do:
`sudo apt-get remove emacs26` 
then the snap keeps working, but as soon as I do:
`sudo apt-get autoremove`
the snap stops working again. 
I can only guess it's missing one of the following packages that `autoremove` gets rid of: `emacs26-common libm17n-0 libotf0 m17n-db`

**Comment by alexmurray** [comment]
I am unable to reproduce this on a clean Ubuntu 18.04 LTS install - see  https://asciinema.org/a/Esqu4vXfiZywsZ6VBtjrnQUsw for my test at reproducing it

**Comment by alexmurray** [comment]
I wonder if there is something specific about your user's emacs configuration which might be causing this? Are you referring to some files which get provided by emacs26-common perhaps?

**Comment by seblemaguer** [comment]
Hello,

the package `cl` has been deprecated in emacs 27. I think you should see where is the `autoloads.pkg.el` which is used. Generally, I think it is a good idea to clean the configuration (by removing any downloaded packages and reinstalling it) when changing the emacs to a new major version.

**Comment by Sleepful** [comment]
I am using the [doom-emacs](https://github.com/hlissner/doom-emacs) configuration but I imagine it would not be an issue, they recommend using emacs27. I will follow @seblemaguer's suggestion and clean my current `~/emacs.d` configuration, I will report back with results.

**Comment by Sleepful** [comment]
Cleaning the configuration did the trick, for doom-emacs in particular I had to `delete ~/.emacs.d/.local then run doom sync to reinstall them`

Thank you

**Comment by hlissner** [comment]
For posterity, in case folks stumble on this or similar issues with Doom Emacs:

**Pre Doom v3.0:** when you change the installed version of Emacs (upgrade or downgrade), Doom users must run `doom sync && doom build`. `doom sync` will regenerate your autoloads files (like `autoloads.pkg.el`) and `doom build` will recompile your packages (byte-code isn't generally forward-compatible across new versions of Emacs).

**Post-Doom v3.0.0:** `doom sync` will be all you need (it will detect changes in Emacs versions and act accordingly).

(v3.0 hasn't been released at the time of writing, but I may forget to update this post later, so...)

Hope this spares someone the heartache of reinstalling everything from scratch!
