### ISSUE TITLE
Window grouping is wrong in gnome

### ISSUE THREAD

**Issue by egh** [alexmurray/emacs-snap#24]
OS: Ubuntu 20.04 with `ubuntu-gnome-desktop`
emacs: snap edge

Steps to reproduce:
1. Close all browser windows
2. `emacs -Q`
3. In `*scratch*` buffer, type `http://example.org`
4. Run `M-x browse-url-at-point`

Expected result: new browser window has correct "grouping" (not sure what to call this, class?)
Actual result: new browser window (firefox) is grouped with emacs

This problem is not unique to the emacs snap: I have the same problem with the slack snap.

Bad result:

![image](https://user-images.githubusercontent.com/22718/107703014-eb502580-6c6f-11eb-877a-446b0200c07c.png)

What it should look like (when starting firefox not from emacs)

![image](https://user-images.githubusercontent.com/22718/107703114-13d81f80-6c70-11eb-9b69-032fe1eb8fb3.png)

**Comment by alexmurray** [comment]
Thanks for the detailed bug report. 

I can reproduce it as well - I found the following discussion thread about this issue - https://forum.snapcraft.io/t/slack-opening-file-browser-firefox-and-chrome-in-the-snaps-context/8969 - which references this bug report https://bugs.launchpad.net/snapd/+bug/1835024 - it would seem if you use the firefox snap as a browser it works as expected but if using the deb then this issue occurs. Perhaps there is some more useful guidance in this bug report - let me know if you find a solution and we can mention it here.

**Comment by egh** [comment]
The problem doesn't seem unique to firefox - I get the same problem with chrome and `eog`. It works as expected with spotify, which I have installed as a snap.

A more succinct error report:
1. `emacs -Q`
2. Ensure firefox (or whatever program is mentioned in (3)) is not running
3. `M-! firefox` (or `google-chrome` or `eog` or similar gui program

**Comment by alexmurray** [comment]
FYI - the emacs snap has code to unset some environment variables as part of it's site file (these environment variables are set  when the emacs snap is launched to ensure it gio etc looks for libraries inside the snap, not on the host filesystem) - and so the site file unsets these after load to ensure if you spawn another process from within Emacs, it doesn't try and use these libraries itself. But if you run emacs with `-Q` this will not get used - so instead you should run it with `-q` so it can still use the site start file etc.

**Comment by alexmurray** [comment]
I am not able to reproduce this issue. Can you please let me know if this is still an issue on your side?

**Comment by egh** [comment]
This problem is fixed for me now. I believe this was fixed upstream. Thanks for following up.
