### ISSUE TITLE
[help] Is it possible to install emacs26?

### ISSUE THREAD

**Issue by avatar-lavventura** [alexmurray/emacs-snap#27]
I was wondering is it possible to install `emacs v26`?

**Comment by rassie** [comment]
Not with this snap, AFAIK. 26.x is the old stable version, however it's still available as `emacs` package in Ubuntu if you are not using the latest 21.04 distribution, e.g. 20.04 LTS. Is there a particular usecase why you need 26.x instead of the current 27.x?
