### ISSUE TITLE
File mode specification error: (wrong-type-argument timerp

### ISSUE THREAD

**Issue by lrstott** [alexmurray/emacs-snap#31]
Ubuntu 21.04
Snap: latest/edge:      28.0.50-master-f85b867 2021-09-02 (1235) 293MB classic

File mode specification error: (wrong-type-argument timerp [t nil nil nil nil nil nil nil nil])
ad-handle-definition: ‘vc-revert’ got redefined

I began seeing this yesterday when trying to open js file with lsp-mode.

**Comment by alexmurray** [comment]
Hmm I can't reproduce this - what LSP server are you using? Can you give some basic instructions to reproduce from a clean install?

**Comment by alexmurray** [comment]
Actually I suspect we have happened to hit this issue from upstream: https://lists.gnu.org/archive/html/emacs-devel/2021-09/msg00107.html - I'll trigger a rebuild of the snap from the latest git snapshot which should hopefully resolve this.

**Comment by alexmurray** [comment]
Can you please try using the latest edge build (28.0.50-master-80d318a) and see if that fixes the issue?

**Comment by lrstott** [comment]
Yes, it seems back to normal as I saw no errors. Thank you sir!
