### ISSUE TITLE
Promote 28.x to beta?

### ISSUE THREAD

**Issue by rassie** [alexmurray/emacs-snap#32]
The release branch fro 28.1 [has been cut](https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-28&id=2750d97543bce12e99a650d748a4d85343d7d229) a couple of months ago. Could you promote 28.x to the beta channel to allow people working with 28.x but wanting to avoid working with possibly-unstable 29.x to avoid breakage? Thanks.

**Comment by alexmurray** [comment]
Currently the [emacs](https://launchpad.net/~alexmurray/+snap/emacs) snap recipe publishes to the beta channel by default - and this builds from the current stable 27.2 tarball. Whilst the [emacs-snapshot](https://launchpad.net/~alexmurray/+snap/emacs-snapshot) recipe publishes to the edge channel. The snapshot recipe builds from the release-28 branch as I feel this is more important to be testing via edge than say master.

Once 28.1 is released, I will update the regular emacs snap recipe to build this and publish it to beta and then will change the snapshot recipe to build from master again (and hence this will be 29.0.50 etc).

So feel free to use edge for now as it will be a weekly build of the release-28 branch until 28.1 is officially released.
