### ISSUE TITLE
Exec format error when running emacs build 1457 on ARM64

### ISSUE THREAD

**Issue by sdoshi** [alexmurray/emacs-snap#34]
When running emacs on Ubuntu 20.04 VM, ARM64 architecture I get "format exec error":

sd@dev:~$ sudo snap remove emacs
emacs removed
sd@dev:~$ sudo snap info emacs
name:      emacs
summary:   GNU Emacs is the extensible self-documenting text editor
publisher: Alex Murray (alexmurray)
store-url: https://snapcraft.io/emacs
contact:   https://github.com/alexmurray/emacs-snap/issues
license:   GPL-3.0+
description: |
  Emacs is the extensible, customizable, self-documenting real-time
  display editor.
  
  Features include:
    * Content-aware editing modes, including syntax coloring, for many file types.
    * Complete built-in documentation, including a tutorial for new users.
    * Full Unicode support for nearly all human scripts.
    * Highly customizable, using Emacs Lisp code or a graphical interface.
    * An entire ecosystem of functionality beyond text editing, including a project
      planner, mail and news reader, debugger interface, calendar, and more.
    * A packaging system for downloading and installing extensions.
  
  This snap is built via the build.snapcraft.io service from the
  snapcraft.yaml definition at https://github.com/alexmurray/emacs-snap to
  ensure source and build transparency.
snap-id: 4gE2S31SnK2LeqsZF8XTPuHOlqlzbqsW
channels:
  latest/stable:    28.1                   2022-04-04 (1457) 248MB classic
  latest/candidate: 28.1                   2022-04-04 (1457) 248MB classic
  latest/beta:      28.1                   2022-04-04 (1457) 248MB classic
  latest/edge:      29.0.50-master-7410099 2022-04-04 (1458) 289MB classic
sd@dev:~$ sudo snap install --classic emacs
emacs 28.1 from Alex Murray (alexmurray) installed
sd@dev:~$ emacs
/snap/emacs/1457/setup-env: 46: exec: /snap/emacs/1457/usr/bin/emacs: Exec format error

sd@dev:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
sd@dev:~$ uname -a
Linux dev 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:44:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by alexmurray** [comment]
Argh.. apologies, will try fix this ASAP. Thanks for reporting this issue.

**Comment by alexmurray** [comment]
This is now resolved - can you please `snap refresh emacs` and it should work as expected. Apologies again for the breakage.

**Comment by sdoshi** [comment]
Fixed. Thank you!
