### ISSUE TITLE
what's the actual version?

### ISSUE THREAD

**Issue by oussamabouchareb** [alexmurray/emacs-snap#46]
it seems that snap thinks I have your latest version which is 28.2, but when I do `emacs --v` it shows me 26.3, so which one is it?

**Comment by alexmurray** [comment]
I suspect you have both the emacs snap and deb installed - what is the output of `which emacs`? Also you could try `/snap/bin/emacs --version`

**Comment by oussamabouchareb** [comment]
I knew I was doing something wrong, thanks man it really helped :)
