### ISSUE TITLE
This just hurts to see

### ISSUE THREAD

**Issue by jnordwick** [alexmurray/emacs-snap#47]
Putting emacs into a snap is like putting your finger your finger in the eye of the FSF. I don't think canonical should be packaging applications that the apps don't do themselves or explicitly ask for it. Even though legal, it seems highly unethical.

**Comment by alexmurray** [comment]
I asked the emacs developers about collaborating on this but there wasn't much interest - https://lists.gnu.org/archive/html/emacs-devel/2019-05/msg00789.html - however there was also no pushback either. As such, I don't see why you think it is unethical - it is free software - anyone is free to use and redistribute it as long as they provide the source - which is done by virtue of providing the snapcraft.yaml recipe in this repo which references the upstream emacs source code. 

Whilst you may not like snaps, over 20k people are happily using the emacs snap.

**Comment by jnordwick** [comment]
If they don't have a provblem, then I don't have a problem, but that post was more about the CI aspect.. Yes, what you are doing is almost certainly legal, but that, not the number of used make it ethical. You also being a canonical worker bad for Canoniocal and its emplouees to be running around package software done by FSF, GNU, and RMS because they done approve of snap.                                                                                                                                                                                                                                                                                                                  

Did you ever get a response from  RMS?  Can always ask him. Would you like to et some clarification. I wo't know his mine, so it would be interesting for me hear itr from hm. There may be a partial sotiion open even.
