### ISSUE TITLE
Edge Pull Frequency

### ISSUE THREAD

**Issue by kantholtz** [alexmurray/emacs-snap#49]
Hello, thank you for providing the snap for Emacs!

I was wondering what the pull frequency from master for the `--edge` version is. (There is an annoying - but already fixed - bug which prohibits the use of `dired`).

**Comment by alexmurray** [comment]
I try and remember to rebuild the edge emacs snap from git master every Monday - this week I have been on vacation so I hadn't yet retriggered this but just for you I have done this now - with any luck in an hour or two a new build should be published to the edge channel. Cheers!
