### ISSUE TITLE
Emacs 29 builds

### ISSUE THREAD

**Issue by sonofjon** [alexmurray/emacs-snap#50]
Can we have Emacs 29 builds please?

**Comment by alexmurray** [comment]
Emacs 29 is not released yet. However we already have builds of the current upstream 'master' branch of emacs published to the edge channel each week (this is now version 30.0.50 iirc). So for now probably best to just use edge. Once upstream officially releases 29.1 I will publish that to the stable channel.

**Comment by sonofjon** [comment]
Yes, I have used the edge channel, but in order to track and provide feedback to the development of Emacs 29 until release, it would be useful to have access to Emacs 29. I believe most advanced users are following the Emacs 29 branch, and not Emacs 30 (the latter IMHO will be more of interest after release of Emacs 29). Just a thought. Currently I am recompiling Emacs 29 myself, every week or so, but it would be nice to have a snap instead.

**Comment by alexmurray** [comment]
emacs-29 builds are now available on the beta channel. Closing this as complete.
