### ISSUE TITLE
Some issue with the latest Emacs update

### ISSUE THREAD

**Issue by olddeuteronomy** [alexmurray/emacs-snap#52]
Hi Alex,

My Emacs snap has been recently updated to

```
snap-id:      4gE2S31SnK2LeqsZF8XTPuHOlqlzbqsW
tracking:     latest/stable
refresh-date: 2 days ago, at 14:07
channels:
  latest/stable:    28.2                   2023-01-19 (1791) 241MB classic
```

Now I get the following trying to activate the `tree-sitter-langs` package:

```
tree-sitter-load: Language load failed: "/snap/emacs/1791/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: 
version `GLIBC_2.32' not found 
(required by /home/magnolia/.emacs.d/elpa/tree-sitter-langs-20230116.538/bin/python.so)"
```

I'm on Pop!_OS 20.10. I had never experienced any problem with the Emacs snap before. Any ideas?

Thanks!

**Comment by alexmurray** [comment]
Hmm it is odd this only just occurred but it is not surprising that are potential mismatches between the libc that Emacs was compiled against and the version on your host operating system - in this case you are running a newer release (20.10) than what emacs was compiled against (20.04) and so yours uses and expects a newer glibc version than what emacs has. Unfortunately I am not sure there is a good way to resolve this at this stage. It is just the nature of trying to deliver a single binary that runs on multiple operating systems - when someone then tries to add in extra binaries (as tree-sitter does) then there will be mismatches.

One possible way to try and resolve this would be to ship gcc inside the emacs snap and try to configure tree-sitter to compile with that compiler against the glibc that is also shipped inside the emacs snap - then they *may* be compatible.

**Comment by olddeuteronomy** [comment]
Hi Alex,

Many thanks for your prompt and detailed response. It makes sense now.

I tend to think that the best and safe way is to build Emacs on my local machine from the scratch.

Thank you again.

**Comment by alexmurray** [comment]
Yes unfortunately I think at this point the emacs snap will not work well for this use-case - apologies.
