### ISSUE TITLE
GLIBC_2.33 errors when installing on Ubuntu 23.04

### ISSUE THREAD

**Issue by gjm** [alexmurray/emacs-snap#57]
I think this is the same problem as in #29

**Comment by alexmurray** [comment]
This is generally a cosmetic issue - does it actually cause emacs to fail to work correctly? For myself I see the following printed on startup:

```
$ emacs -q

(emacs:1077112): Gtk-WARNING **: 23:20:05.470: /snap/emacs/1970/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libibus-1.0.so.5)

(emacs:1077112): Gtk-WARNING **: 23:20:05.471: Loading IM context type 'ibus' failed
```

But emacs works correctly.

I can try and look into fixing this but it would be good to know if it is causing an actual issue. Thanks.

**Comment by gjm** [comment]
Yes I get the same output. Emacs starts and seems to work fine, yes. 

If it's only cosmetic and harmless is there a simple way to omit the output? Other than redirecting it?

**Comment by alexmurray** [comment]
With 3ed058eb055fc6e8942315da993ab7e3e481c897 this should now be fixed - new snaps will build shortly and be published to beta etc in the next hour or two. If you could please refresh to this and let me know if it is fixed for you that would be great.

**Comment by gjm** [comment]
Nevermind... seems to have updated itself silently... Errors are gone! Thanks!

**Comment by martibosch** [comment]
I am encountering this issue with ubuntu 22.04 *since* the latest build, i.e.:

```
GNU Emacs 29.1
Development version cf57ec68c2a5 on master branch; build date 2023-08-04.
```

More precisely, the following error occurs when running `jupyter-run-repl` on [my setup](https://github.com/martibosch/snakemacs):

```
byte-code: Module could not be opened: "/home/martibosch/snakemacs/straight/build/zmq/emacs-zmq.so", "/snap/emacs/2163/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/martibosch/snakemacs/straight/build/zmq/emacs-zmq.so)"
```

I have tried reinstalling emacs and re-compiling everything but I still encounter this. Any clues of how my I fix it?

Thank you. Best,
Martí

**Comment by alexmurray** [comment]
@martibosch please see https://github.com/alexmurray/emacs-snap/issues/66 - the issue you are seeing is specific to loading modules into emacs.

**Comment by nicolasshu** [comment]
https://github.com/nnicandro/emacs-zmq/issues/48#issuecomment-2250719671
