### ISSUE TITLE
Can't install treesit-auto: "No such file or directory, cus-edit"

### ISSUE THREAD

**Issue by solace-rcampbell** [alexmurray/emacs-snap#59]
I'm trying to install treesit-auto using a snap version of emacs "GNU Emacs 29.0.90".

When I run the melpa instructions I get this error:
package--save-selected-packages: Cannot open load file: No such file or directory, cus-edit

I opened a bug with treesit-auto (https://github.com/renzmann/treesit-auto/issues/45).  They said that "cus-edit" is built-in to Emacs, and that the problem might be with the snap.

**Comment by alexmurray** [comment]
I am not able to reproduce this error with the current emacs-29 version of the emacs snap:

```
$ emacs -q --eval "(progn (if (require 'cus-edit nil t) (print \"loaded cus-edit\" #'external-debugging-output) (print \"error loading cus-edit\" #'external-debugging-output)) (kill-emacs))"

"loaded cus-edit"
```

- I notice you mention "GNU Emacs 29.0.90". - but the current version of emacs 29 from the emacs-snap is 29.0.92 - can you please try and refresh your snap install of emacs?

```
sudo snap refresh --beta emacs
```

**Comment by solace-rcampbell** [comment]
Thanks.  I can't reproduce this problem with the newest version.
