### ISSUE TITLE
gtklp doesn't work from within emacs due to library issues

### ISSUE THREAD

**Issue by dmusican** [alexmurray/emacs-snap#63]
I'm on Ubuntu 22.04, and use gtklp as method for printing, e.g.

```
(setq lpr-command "gtklp")
(setq ps-lpr-command "gtklp")
```

I've installed `gtklp` directly from the Ubuntu apt repository. Generally works well, but when running emacs from this snap and I try to print, I get...

```gtklp: symbol lookup error: /snap/emacs/2137/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/../../../../../../lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE```

**Comment by alexmurray** [comment]
Thanks for reporting this issue - I have just committed a change that I hope should fix this - new builds of the snap should then be created automatically and published to the beta channel - if you could please test this and report back that would be great.

**Comment by dmusican** [comment]
I just tried updating from the beta channel, and the problem is fixed. That was really fast. Thank you!

**Comment by alexmurray** [comment]
You're welcome - thanks again for reporting the issue.
