### ISSUE TITLE
User <name> has no home directory

### ISSUE THREAD

**Issue by gigem** [alexmurray/emacs-snap#68]
I'm using the emacs 29 snap on Ubuntu 22.04 LTS.  At startup, emacs reports the following.

 ■  Error (initialization): User dengel has no home directory

I'm pretty sure the problem stems from our use of sssd (configured in /etc/nsswitch.conf) with Microsoft Active Directory for login authentication and user info.  Adding an entry to /etc/passwd for the user causes the emacs error to go away.  Doing so causes other system issues so is not an acceptable solution.

I suspect the snap needs to be built with some extra NSS/SSS packages to work with our configuration.  libnss-sss and libsss-nss-idmap0 look like good candidates.

**Comment by alexmurray** [comment]
I have promoted the emacs 29.1 snap to stable with the fix from #69 - closing this as fixed. Thanks again @gigem.
