### ISSUE TITLE
Thanks for making emacs available through snap

### ISSUE THREAD

**Issue by rishabh96b** [alexmurray/emacs-snap#8]
Hey Alex,
This is just to give kudos to you for bringing this crazy stuff in the snap store. :1st_place_medal: I wanted to use emacs and after a single search I got to know that it's easily available through snap. Thanks for making it this easy. 

Please feel free to close this issue. :smiley:

**Comment by alexmurray** [comment]
Thanks for the positive feedback, this has really brightened my day :smile:
