### ISSUE TITLE
emacs snap 29.1 requires manual glib-2.0 schema files on old systems

### ISSUE THREAD

**Issue by mvk** [alexmurray/emacs-snap#80]
while running on old rhel7 systems, the snap manages to execute,
but if you try to use file chooser dialog, there is an issue:
![Sun Dec 10 2023 09_45_55 GMT+0200 (Israel Standard Time)](https://github.com/alexmurray/emacs-snap/assets/152877/4760e87b-72c4-45bb-ac31-9b51478589f2)

After further digging:
1. there is an issue with `glib-2.0` schema files mismatch
2. the correct schema files are shipped with the package
3. if I run: `snap run --shell emacs`, and then inspect `XDG_DATA_DIRS`, the variable lacks any that snap specific folders

Workaround without changing the snap:
1. copy the schema files to system location, e.g. as root:
```
cp /snap/emacs/2307/usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml /usr/share/glib-2.0/schemas`
```
2. restart the snap application

I am noticing that newer versions of snap, e.g. version `30.0.50-master-a470dfb` already has `XDG_DATA_DIRS` with the right snap folder.

Can you please repackage the snap for 29.1  with the same fix ?

**Comment by alexmurray** [comment]
I expect that perhaps the issue here may be due to the recent changes in gsettings schema handling in https://github.com/alexmurray/emacs-snap/commit/84a5da06c91d876f14af4a745e7e9e21cf82ddcb

**Comment by alexmurray** [comment]
Closing this as the linked PR was closed as not needed.
