### ISSUE TITLE
Update stable channel to 29.2?

### ISSUE THREAD

**Issue by fmqa** [alexmurray/emacs-snap#82]
Hello,

Emacs 29.2 has been released for about a month now, yet the stable channel is still on 29.1
Are there any show-stoppers that preclude the promotion of 29.2 to stable? 

TYI

**Comment by alexmurray** [comment]
Hi - thanks for the reminder - no, I am not aware of any showstoppers - but I wanted to get some incidental testing from the few folks using the beta channel etc (since there is about 100x times as many users of the stable channel in comparison). I will promote it to stable now. Thanks.

**Comment by alexmurray** [comment]
```
$ snap info emacs | grep latest/stable
  latest/stable:    29.2                   2024-02-20 (2372) 353MB classic
```
