### ISSUE TITLE
29.2 rectangle-mark-mode error

### ISSUE THREAD

**Issue by FrankBattaglia** [alexmurray/emacs-snap#84]
On a fresh install of emacs 29.2, whenever I try to use `rectangle-mark-mode`, I get the following error:

```comp-trampoline-search: eln file inconsistent with current runtime configuration, please recompile: "~/.emacs.d/eln-cache/29.2-f682e022/subr--trampoline-726567696f6e2d626567696e6e696e67_region_beginning_0.eln"```

I have removed all packages and removed my `~/.emacs.d/init.el`.  There are no other errors in the `*Messages*` buffer.

Ubuntu 22.04.4

**Comment by FrankBattaglia** [comment]
Yes; if I remove the file and restart emacs, it re-creates the file with the same error

**Comment by alexmurray** [comment]
Also are you able to try with `emacs -q`?

**Comment by alexmurray** [comment]
Just confirming I can reproduce it with `emacs -q`

**Comment by alexmurray** [comment]
Another report https://www.reddit.com/r/emacs/s/xcON7GmZYL

**Comment by alexmurray** [comment]
I wonder if this is a recent issue (ie only within the last couple days)? If so perhaps it was caused by the recent change to fake invocation name for #83

**Comment by etegan** [comment]
Just to add some related errors with a fresh snap installation:

Error (use-package): evil/:catch: eln file inconsistent with current runtime configuration, please recompile: "~/.emacs.d/eln-cache/29.2-f682e022/subr--trampoline-7365742d77696e646f772d627566666572_set_window_buffer_0.eln"
Error (use-package): magit/:catch: eln file inconsistent with current runtime configuration, please recompile: "~/.emacs.d/eln-cache/29.2-f682e022/subr--trampoline-6d616b652d70726f63657373_make_process_0.eln"
Error (use-package): dap-mode/:catch: eln file inconsistent with current runtime configuration, please recompile: "~/.emacs.d/eln-cache/29.2-f682e022/subr--trampoline-64657363726962652d6275666665722d62696e64696e6773_describe_buffer_bindings_0.eln"

**Comment by alexmurray** [comment]
Apologies for this issue folks - I have a proposed fix which should hopefully resolve this - the snap should automatically build and be published to the beta channel in a few hours - if someone could please test this once it's available and let me know if it fixes this that would be great. You will have to remove the mentioned 'inconsistent' eln files but they should then get regenerated correctly. Thanks.

**Comment by kwist-sgr** [comment]
Hi folks. 
Two days ago, after updating to version 29.2, I encountered the same problem.
Yesterday I installed version 30.0.50-master-4a8d3c5 (latest/edge), and it doesn't have this problem

**Comment by achambers8472** [comment]
> Apologies for this issue folks - I have a proposed fix which should hopefully resolve this - the snap should automatically build and be published to the beta channel in a few hours - if someone could please test this once it's available and let me know if it fixes this that would be great. You will have to remove the mentioned 'inconsistent' eln files but they should then get regenerated correctly. Thanks.

`sudo snap refresh emacs --channel=latest/beta` and deleting the offending `.eln` worked for me a few minutes ago, cheers!

**Comment by alexmurray** [comment]
Thanks for confirming, I'll promote it to stable. Cheers.

**Comment by nmsalgueiro** [comment]
Fix worked in my system too. Thanks!

**Comment by alexmurray** [comment]
Excellent, apologies again folks. Please let me know if you have any other issues.

**Comment by FrankBattaglia** [comment]
Just following up to confirm it seems to have resolved the issue for me as well.  Thanks!
