### ISSUE TITLE
Tree-sitter not loading

### ISSUE THREAD

**Issue by d-hr** [alexmurray/emacs-snap#86]
Hi,

tree-sitter does not load in emacs 29.2 (across all channels) since the February 27th update of the snap:
``` ■  Warning (treesit): Cannot activate tree-sitter, because language grammar for rust is unavailable (not-found): (libtree-sitter-rust libtree-sitter-rust.0 libtree-sitter-rust.0.0 libtree-sitter-rust.so libtree-sitter-rust.so.0 libtree-sitter-rust.so.0.0) No such file or directory```
According to this [reddit entry](https://www.reddit.com/r/emacs/comments/131629d/emacs_29_cant_load_treesitter_grammer/), the snap needs to be build with these libraries.

Thank's for maintaining the snap.

Best,
David

**Comment by alexmurray** [comment]
It is built with tree sitter support already. Can you try reinstalling the tree sitter grammars?

**Comment by d-hr** [comment]
Thanks, this solved the error. I did not expect that the solution would be this easy 😅
