### ISSUE TITLE
Emacs pretest on the Beta channel

### ISSUE THREAD

**Issue by sonofjon** [alexmurray/emacs-snap#95]
Hi,

just as last year, can we please have the Emacs pretest release (for version 30) on the Beta channel? See my comment in #50 why this is useful.

Currently we have version 29.4 duplicated on the Stable, Candidate and Beta channels. IMHO it would be more useful to devote Candidate for nightly builds (currently version 31), Beta for Pretest releases (currently version 30.0.92), and obviously Stable for the currently stable release (currently verion 29.4). This scheme should be kept for for future releases: 31, 32, 33, etc., only shifting the numbers, so for exmple, approaching stable realease of version 31 we should have: Stable: v30, Beta: v31-pretest, Candidate: v32-nightly-build, and so on...  

What do you think?

**Comment by alexmurray** [comment]
In general whilst your suggestion makes sense, we need somewhere to publish builds to-be-tested before we then promote them to stable - so there needs to be at least 1 grade before stable where (hopefully) stable builds get autopublishd into, then they get tested, and promoted into stable.

Which would leave something like:

snapshot (emacs-31) -> edge
pretest (emacs-30) -> beta
stable (emacs-29) -> candidate
manually verified stable (emacs-29) -> stable

I'll see if I can rejig to existing build recipes to match this.

**Comment by alexmurray** [comment]
Ok, builds for the most recent pretest tarball 30.0.92 should now be on the beta channel - let me know if anything seems amiss but I will close this issue for now then.

**Comment by alexmurray** [comment]
```
$ snap info emacs
name:      emacs
summary:   GNU Emacs is the extensible self-documenting text editor
publisher: Alex Murray (alexmurray✪)
store-url: https://snapcraft.io/emacs
contact:   https://github.com/alexmurray/emacs-snap/issues
license:   GPL-3.0+
description: |
  Emacs is the extensible, customizable, self-documenting real-time
  display editor.
  
  Features include:
    * Content-aware editing modes, including syntax coloring, for many file types.
    * Complete built-in documentation, including a tutorial for new users.
    * Full Unicode support for nearly all human scripts.
    * Highly customizable, using Emacs Lisp code or a graphical interface.
    * An entire ecosystem of functionality beyond text editing, including a project
      planner, mail and news reader, debugger interface, calendar, and more.
    * A packaging system for downloading and installing extensions.
  
  This snap is built via the build.snapcraft.io service from the
  snapcraft.yaml definition at https://github.com/alexmurray/emacs-snap to
  ensure source and build transparency.
commands:
  - emacs.ctags
  - emacs.ebrowse
  - emacs
  - emacs.emacsclient
  - emacs.etags
snap-id:      4gE2S31SnK2LeqsZF8XTPuHOlqlzbqsW
tracking:     latest/beta
refresh-date: today at 12:14 ACDT
channels:
  latest/stable:    29.4                   2024-06-25 (2504) 376MB classic
  latest/candidate: 29.4                   2024-06-25 (2504) 376MB classic
  latest/beta:      30.0.92                2024-11-26 (2568) 405MB classic
  latest/edge:      31.0.50-master-e7810ab 2024-10-22 (2547) 343MB classic
  pgtk/stable:      –                                              
  pgtk/candidate:   –                                              
  pgtk/beta:        –                                              
  pgtk/edge:        30.0.50-master-a470dfb 2024-01-30 (2385) 357MB classic
  28.x/stable:      28.2                   2023-09-23 (2192) 241MB classic
  28.x/candidate:   ↑                                              
  28.x/beta:        28.2                   2023-12-10 (2306) 241MB classic
  28.x/edge:        ↑                                              
installed:          30.0.92                           (2568) 405MB classic
```
